default:
  image: docker:latest

  services:
    - docker:dind

  before_script:
    - apk --no-cache add docker-compose
    - docker info
    - docker-compose --version

test:
  script:
    - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
